name=ESP32-S3-Watch-Engine
version=1.0.0
author=AirysDark
maintainer=AirysDark
sentence=Graphics and 3D rendering engine for ESP32-S3-LCD-1.69.
paragraph=Framebuffer, Z-buffer, 2D graphics, widgets, texture mapping and software 3D rendering.
category=Display
architectures=esp32